package com.james.tinkerscalibration.contents;

import com.james.tinkerscalibration.TinkersCalibration;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Material;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class TinkersCalibrationBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, TinkersCalibration.MODID);
    private static final BlockBehaviour.Properties ORE = DropExperienceBlock.Properties.of(Material.STONE).requiresCorrectToolForDrops().strength(2.5F, 5f).sound(SoundType.STONE);
    private static final BlockBehaviour.Properties METAL = Block.Properties.of(Material.METAL).requiresCorrectToolForDrops().strength(5F, 1200f).sound(SoundType.METAL);
    public static RegistryObject<Block> lindsteel_block = BLOCKS.register("lindsteel_block", () -> new Block(METAL));
    public static RegistryObject<Block> emperorslime_block = BLOCKS.register("emperorslime_block", () -> new Block(METAL));
    public static RegistryObject<Block> fazelle_block = BLOCKS.register("fazelle_block", () -> new Block(METAL));
    public static RegistryObject<Block> titanium_block = BLOCKS.register("titanium_block", () -> new Block(METAL));
    public static RegistryObject<Block> jazz_block = BLOCKS.register("jazz_block", () -> new Block(METAL));
    public static RegistryObject<Block> mandite_block = BLOCKS.register("mandite_block", () -> new Block(METAL));
    public static RegistryObject<Block> deepslate_titanium_ore = BLOCKS.register("deepslate_titanium_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> titanium_ore = BLOCKS.register("titanium_ore", () -> new Block(ORE));
    public static RegistryObject<Block> stellarium_ore = BLOCKS.register("stellarium_ore", () -> new Block(ORE));
    public static RegistryObject<Block> immersed_silver_ore = BLOCKS.register("immersed_silver_ore", () -> new Block(ORE));
    public static RegistryObject<Block> inert_witherium_ore = BLOCKS.register("inert_witherium_ore", () -> new Block(ORE));
    public static RegistryObject<Block> hothium_ore = BLOCKS.register("hothium_ore", () -> new Block(ORE));
    public static RegistryObject<Block> magiga_ore = BLOCKS.register("magiga_ore", () -> new Block(ORE));
    public static RegistryObject<Block> tonium_ore = BLOCKS.register("tonium_ore", () -> new Block(ORE));
    public static RegistryObject<Block> corundum_ore = BLOCKS.register("corundum_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> nitre_ore = BLOCKS.register("nitre_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    //public static RegistryObject<Block> pyrophyllite_ore = BLOCKS.register("pyrophyllite_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(2,5)));
    public static RegistryObject<Block> spinel_ore = BLOCKS.register("spinel_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> talcum_ore = BLOCKS.register("talcum_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    public static RegistryObject<Block> tourmaline_ore = BLOCKS.register("tourmaline_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    //public static RegistryObject<Block> sunstone_ore = BLOCKS.register("sunstone_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    //public static RegistryObject<Block> moonstone_ore = BLOCKS.register("moonstone_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> vibrating_crystal_ore = BLOCKS.register("vibrating_crystal_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(2,6)));
    public static RegistryObject<Block> deepslate_stellarium_ore = BLOCKS.register("deepslate_stellarium_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> deepslate_immersed_silver_ore = BLOCKS.register("deepslate_immersed_silver_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> deepslate_hothium_ore = BLOCKS.register("deepslate_hothium_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> deepslate_magiga_ore = BLOCKS.register("deepslate_magiga_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> deepslate_tonium_ore = BLOCKS.register("deepslate_tonium_ore", () -> new Block(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE_GOLD_ORE)));
    public static RegistryObject<Block> deepslate_corundum_ore = BLOCKS.register("deepslate_corundum_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> deepslate_nitre_ore = BLOCKS.register("deepslate_nitre_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    //public static RegistryObject<Block> deepslate_pyrophyllite_ore = BLOCKS.register("deepslate_pyrophyllite_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(2,5)));
    public static RegistryObject<Block> deepslate_spinel_ore = BLOCKS.register("deepslate_spinel_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> deepslate_talcum_ore = BLOCKS.register("deepslate_talcum_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    public static RegistryObject<Block> deepslate_tourmaline_ore = BLOCKS.register("deepslate_tourmaline_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(1,4)));
    //public static RegistryObject<Block> deepslate_sunstone_ore = BLOCKS.register("deepslate_sunstone_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    //public static RegistryObject<Block> deepslate_moonstone_ore = BLOCKS.register("deepslate_moonstone_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(4,8)));
    public static RegistryObject<Block> deepslate_vibrating_crystal_ore = BLOCKS.register("deepslate_vibrating_crystal_ore", () -> new DropExperienceBlock(ORE, UniformInt.of(2,6)));
    public static RegistryObject<Block> stellarium_block = BLOCKS.register("stellarium_block", () -> new Block(METAL));
    public static RegistryObject<Block> immersed_silver_block = BLOCKS.register("immersed_silver_block", () -> new Block(METAL));
    public static RegistryObject<Block> inert_witherium_block = BLOCKS.register("inert_witherium_block", () -> new Block(METAL));
    public static RegistryObject<Block> halleium_block = BLOCKS.register("halleium_block", () -> new Block(METAL));
    public static RegistryObject<Block> hothium_block = BLOCKS.register("hothium_block", () -> new Block(METAL));
    public static RegistryObject<Block> steamium_block = BLOCKS.register("steamium_block", () -> new Block(METAL));
    public static RegistryObject<Block> magiga_block = BLOCKS.register("magiga_block", () -> new Block(METAL));
    public static RegistryObject<Block> tonium_block = BLOCKS.register("tonium_block", () -> new Block(METAL));
    public static RegistryObject<Block> oraclium_block = BLOCKS.register("oraclium_block", () -> new Block(METAL));
    public static RegistryObject<Block> witherium_block = BLOCKS.register("witherium_block", () -> new Block(METAL));
    public static RegistryObject<Block> alumite_block = BLOCKS.register("alumite_block", () -> new Block(METAL));
    public static RegistryObject<Block> corundum_block = BLOCKS.register("corundum_block", () -> new Block(METAL));
    public static RegistryObject<Block> nitre_block = BLOCKS.register("nitre_block", () -> new Block(METAL));
    //public static RegistryObject<Block> pyrophyllite_block = BLOCKS.register("pyrophyllite_block", () -> new Block(METAL));
    public static RegistryObject<Block> spinel_block = BLOCKS.register("spinel_block", () -> new Block(METAL));
    public static RegistryObject<Block> talcum_block = BLOCKS.register("talcum_block", () -> new Block(METAL));
    public static RegistryObject<Block> tourmaline_block = BLOCKS.register("tourmaline_block", () -> new Block(METAL));
    //public static RegistryObject<Block> sunstone_block = BLOCKS.register("sunstone_block", () -> new Block(METAL));
    //public static RegistryObject<Block> moonstone_block = BLOCKS.register("moonstone_block", () -> new Block(METAL));
    public static RegistryObject<Block> vibrating_crystal_block = BLOCKS.register("vibrating_crystal_block", () -> new Block(METAL));
    public static RegistryObject<Block> iceland_spar_block = BLOCKS.register("iceland_spar_block", () -> new Block(METAL));
    public static RegistryObject<Block> lizanite_block = BLOCKS.register("lizanite_block", () -> new Block(METAL));
    public static RegistryObject<Block> topaz_block = BLOCKS.register("topaz_block", () -> new Block(METAL));
    public static RegistryObject<Block> prehnite_block = BLOCKS.register("prehnite_block", () -> new Block(METAL));

}
